import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import vuePlugin from 'esbuild-plugin-vue3';
import fs from 'fs';

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Obsidian requires that the style file is called styles.css
const renameCSSFile = () => fs.rename('main.css', 'styles.css', () => { });

try {
	await esbuild.build({
		banner: {
			js: banner,
		},
		entryPoints: ['src/main.ts'],
		bundle: true,
		external: [
			'obsidian',
			'electron',
			'@codemirror/autocomplete',
			'@codemirror/closebrackets',
			'@codemirror/collab',
			'@codemirror/commands',
			'@codemirror/comment',
			'@codemirror/fold',
			'@codemirror/gutter',
			'@codemirror/highlight',
			'@codemirror/history',
			'@codemirror/language',
			'@codemirror/lint',
			'@codemirror/matchbrackets',
			'@codemirror/panel',
			'@codemirror/rangeset',
			'@codemirror/rectangular-selection',
			'@codemirror/search',
			'@codemirror/state',
			'@codemirror/stream-parser',
			'@codemirror/text',
			'@codemirror/tooltip',
			'@codemirror/view',
			...builtins],
		plugins: [vuePlugin()],
		format: 'cjs',
		watch: prod ? false : {
			onRebuild: renameCSSFile
		},
		target: 'es2016',
		logLevel: "info",
		sourcemap: prod ? false : 'inline',
		treeShaking: true,
		outfile: 'main.js',

	});
	renameCSSFile();
}
catch (e) {
	console.error(e);
	process.exit(1)
}
